### ISSUE TITLE
Create data collection class for GAs

### ISSUE THREAD

**Issue by colefuerth** [kilbouri/comp3710-group-project-1#12]
GAs are getting bloated with all the data collection I've added. Ideally, agents should be agile and lightweight.

**We should strip all the data collection out of the agent and make a separate class for data collection on GAs.** This class can be bloated with data collection. Keep data on individuals during testing. We can keep lots of individuals in a population for learning, but testing data will be collected on a small number of trained individuals.

**Comment by kilbouri** [comment]
Closing for archiving.
