### ISSUE TITLE
Genetic Mutations Manager/Environment

### ISSUE THREAD

**Issue by colefuerth** [kilbouri/comp3710-group-project-1#4]
**this is a back burner item, this comes after all the simple agents are working and actually testable**

- [x] have a population of 100
- [x] test them against various agents
- [x] Mutate the top 5-10% to produce next generation
- [ ] Compare trained agents to different agents

Since we have limited time, it is probably best to compare GA to each other agent once. Each gets a training session, then a test session. There is such a thing as too much data

**Comment by kilbouri** [comment]
Closing for archiving.
